import 'package:flutter/material.dart';

class Product {
  final String image, title, description;
  final int price, size, id;
  final Color color;
  Product({
    @required this.id,
//    @required this.quantity,
    @required this.image,
    @required  this.title,
    @required this.price,
    @required this.description,
    @required this.size,
    @required this.color,
  });
}


List<Product> products = [
  Product(
      id: 1,
      title: "Office Code",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/bag_1.png",
      color: Color(0xFF3D82AE)),

  Product(
    id: 7,
    title: "Jacket",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/jacket8.png",
    color: Colors.grey.shade100,
  ),

  Product(
      id: 3,
      title: "Hang Top",
      price: 234,
      size: 10,
      description: dummyText,
      image: "assets/bag_3.png",
      color: Color(0xFF989493)),

  Product(
    id: 9,
    title: "Sports Shoes",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/shoe1.jpg",
    color: Colors.grey.shade100,
  ),


  Product(
      id: 2,
      title: "Belt Bag",
      price: 234,
      size: 8,
      description: dummyText,
      image: "assets/bag_2.png",
      color: Color(0xFFD3A984)),

  Product(
    id: 12,
    title: "t-shirt",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/t-shirt6.jpg",
    color: Colors.grey.shade100,
  ),


  Product(
    id: 13,
    title: "Sports Shoes",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/shoe1.jpg",
    color: Colors.grey.shade100,
  ),


  Product(
    id: 11,
    title: "t-shirt",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/t-shirt1.jpg",
    color: Colors.grey.shade100,
  ),

  Product(
      id: 4,
      title: "Old Fashion",
      price: 234,
      size: 11,
      description: dummyText,
      image: "assets/bag_4.png",
      color: Color(0xFFE6B398)),
  Product(
      id: 5,
      title: "Office Code",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/bag_5.png",
      color: Color(0xFFFB7883)),

  Product(
    id: 14,
    title: "Jacket",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/jacket8.png",
    color: Colors.grey.shade100,
  ),

  Product(
    id: 8,
    title: "Office Code",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/t-shirt2.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 15,
    title: "Sports Shoes",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/shoe1.jpg",
    color: Colors.grey.shade100,
  ),
  Product(
    id: 10,
    title: "Beau trouser",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/trouser6.jpg",
    color: Colors.grey.shade100,
  ),
  Product(
    id: 16,
    title: "Beau trouser",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/trouser4.jpg",
    color: Colors.grey.shade100,
  ),
  Product(
    id: 17,
    title: "Beau Jacket",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/jacket3.jpg",
    color: Colors.grey.shade100,
  ),
  Product(
    id: 18,
    title: "Sports Shoes",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/shoe4.jpg",
    color: Colors.grey.shade100,
  ),
  Product(
    id: 19,
    title: "Beau Jacket",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/jacket4.jpg",
    color: Colors.grey.shade100,
  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),
//  Product(
//    id: 6,
//    title: "Office Code",
//    price: 234,
//    size: 12,
//    description: dummyText,
//    image: "assets/bag_6.png",
//    color: Color(0xFFAEAEAE),
//  ),


];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing\n.When an unknown printer took a galley.";
